language: perl
perl:
  - "5.8.1"
  - "5.8.9"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
matrix:
  include:
    - perl: 5.18.2
      env: COVERAGE=1         # enables coverage+coveralls reporting
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/tobyink/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --toolchain  # installs a vaguely recent EUMM, Exporter
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - prove -l $(test-dirs)
after_success:
  - coverage-report

